/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author AEE
 */
public class JPanel_Pedido extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Pedido
     */
    public JPanel_Pedido() {
        initComponents();
        jButtonHacerPedido.setEnabled(false);
        jLabelBalones.setIcon(setIcono("/Imagenes/Balones.png",jLabelBalones));
   
       
    }
    
    //Métodos para íconos de los botones
    
    public Icon setIcono(String url, JLabel label){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = 418;
        int alto = 340;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    public void BloquearCampos(boolean d){
        jTextFieldC1.setEditable(!d);
        jTextFieldC2.setEditable(!d);
        jTextFieldC3.setEditable(!d);
        jTextFieldC4.setEditable(!d);
        jTextFieldC5.setEditable(!d);
        jTextFieldC6.setEditable(!d);
        jTextFieldC7.setEditable(!d);
        jTextFieldC8.setEditable(!d);
        jTextFieldC9.setEditable(!d);
    }
    public int CalcularTotal(){
        jLabelS1.setText("S/."+Integer.parseInt(jLabelP1.getText().substring(3))*Integer.parseInt(jTextFieldC1.getText()));
        jLabelS2.setText("S/."+Integer.parseInt(jLabelP2.getText().substring(3))*Integer.parseInt(jTextFieldC2.getText()));
        jLabelS3.setText("S/."+Integer.parseInt(jLabelP3.getText().substring(3))*Integer.parseInt(jTextFieldC3.getText()));
        jLabelS4.setText("S/."+Integer.parseInt(jLabelP4.getText().substring(3))*Integer.parseInt(jTextFieldC4.getText()));
        jLabelS5.setText("S/."+Integer.parseInt(jLabelP5.getText().substring(3))*Integer.parseInt(jTextFieldC5.getText()));
        jLabelS6.setText("S/."+Integer.parseInt(jLabelP6.getText().substring(3))*Integer.parseInt(jTextFieldC6.getText()));
        jLabelS7.setText("S/."+Integer.parseInt(jLabelP7.getText().substring(3))*Integer.parseInt(jTextFieldC7.getText()));
        jLabelS8.setText("S/."+Integer.parseInt(jLabelP8.getText().substring(3))*Integer.parseInt(jTextFieldC8.getText()));
        jLabelS9.setText("S/."+Integer.parseInt(jLabelP9.getText().substring(3))*Integer.parseInt(jTextFieldC9.getText()));
        int suma=                   Integer.parseInt(jLabelS1.getText().substring(3))+Integer.parseInt(jLabelS2.getText().substring(3))+
                                    Integer.parseInt(jLabelS3.getText().substring(3))+Integer.parseInt(jLabelS4.getText().substring(3))+
                                    Integer.parseInt(jLabelS5.getText().substring(3))+Integer.parseInt(jLabelS6.getText().substring(3))+
                                    Integer.parseInt(jLabelS7.getText().substring(3))+Integer.parseInt(jLabelS8.getText().substring(3))+
                                    Integer.parseInt(jLabelS9.getText().substring(3));
        return suma;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldC1 = new javax.swing.JTextField();
        jTextFieldC2 = new javax.swing.JTextField();
        jTextFieldC3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldC4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldC5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldC6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldC7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldC8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldC9 = new javax.swing.JTextField();
        jLabelBalones = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jLabelP2 = new javax.swing.JLabel();
        jLabelP3 = new javax.swing.JLabel();
        jLabelP4 = new javax.swing.JLabel();
        jLabelP5 = new javax.swing.JLabel();
        jLabelP6 = new javax.swing.JLabel();
        jLabelP7 = new javax.swing.JLabel();
        jLabelP8 = new javax.swing.JLabel();
        jLabelP9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButtonHacerPedido = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabelS1 = new javax.swing.JLabel();
        jLabelS2 = new javax.swing.JLabel();
        jLabelS3 = new javax.swing.JLabel();
        jLabelS4 = new javax.swing.JLabel();
        jLabelS5 = new javax.swing.JLabel();
        jLabelS6 = new javax.swing.JLabel();
        jLabelS7 = new javax.swing.JLabel();
        jLabelS8 = new javax.swing.JLabel();
        jLabelS9 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tipo");

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("M-4 (113 L)");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("M-2(42 L)");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("ML-6 (165 L)");

        jTextFieldC1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC1.setText("0");
        jTextFieldC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jTextFieldC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldC1ActionPerformed(evt);
            }
        });

        jTextFieldC2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC2.setText("0");
        jTextFieldC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jTextFieldC3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC3.setText("0");
        jTextFieldC3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jTextFieldC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldC3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("M-6 (164 L)");

        jTextFieldC4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC4.setText("0");
        jTextFieldC4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jTextFieldC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldC4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("M-7 (198 L)");

        jTextFieldC5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC5.setText("0");
        jTextFieldC5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("M-9 (255 L)");

        jTextFieldC6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC6.setText("0");
        jTextFieldC6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("M-15 (425 L)");

        jTextFieldC7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC7.setText("0");
        jTextFieldC7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("M-22 (640 L)");

        jTextFieldC8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC8.setText("0");
        jTextFieldC8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jTextFieldC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldC8ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("M-24 (680 L)");

        jTextFieldC9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextFieldC9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldC9.setText("0");
        jTextFieldC9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jLabelBalones.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Precio");

        jLabelP1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP1.setText("S/.80");

        jLabelP2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP2.setText("S/.100");

        jLabelP3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP3.setText("S/.150");

        jLabelP4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP4.setText("S/.200");

        jLabelP5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP5.setText("S/.250");

        jLabelP6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP6.setText("S/.300");

        jLabelP7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP7.setText("S/.400");

        jLabelP8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP8.setText("S/.500");

        jLabelP9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelP9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP9.setText("S/.550");

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Cantidad");

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Total");

        jButtonHacerPedido.setBackground(new java.awt.Color(102, 102, 255));
        jButtonHacerPedido.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButtonHacerPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHacerPedido.setText("HACER PEDIDO");
        jButtonHacerPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Subtotal");

        jLabelS1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS1.setText("S/.0");

        jLabelS2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS2.setText("S/.0");

        jLabelS3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS3.setText("S/.0");

        jLabelS4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS4.setText("S/.0");

        jLabelS5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS5.setText("S/.0");

        jLabelS6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS6.setText("S/.0");

        jLabelS7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS7.setText("S/.0");

        jLabelS8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS8.setText("S/.0");

        jLabelS9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelS9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelS9.setText("S/.0");

        jLabelTotal.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("S/.0");

        jButtonCancelar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCancelar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonCalcular.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCalcular.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButtonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcular.setText("CALCULAR");
        jButtonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelP6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jLabelP5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelP9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldC9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(jTextFieldC8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldC3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelS6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelS9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBalones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButtonCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHacerPedido)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBalones, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelP1)
                            .addComponent(jTextFieldC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelP2)))
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelS2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP5)
                            .addComponent(jLabel9)
                            .addComponent(jLabelS5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP6)
                            .addComponent(jLabel10)
                            .addComponent(jLabelS6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP7)
                            .addComponent(jLabel11)
                            .addComponent(jLabelS7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP8)
                            .addComponent(jLabel12)
                            .addComponent(jLabelS8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldC9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP9)
                            .addComponent(jLabel13)
                            .addComponent(jLabelS9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabelS1))
                            .addComponent(jLabel26)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabelS3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelS4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHacerPedido)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonCalcular))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldC3ActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        jLabelTotal.setText("S/."+CalcularTotal());
        BloquearCampos(true);
        jButtonHacerPedido.setEnabled(true);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        BloquearCampos(false);
        jButtonHacerPedido.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldC4ActionPerformed

    private void jTextFieldC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldC8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldC8ActionPerformed

    private void jTextFieldC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldC1ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jTextFieldC1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonHacerPedido;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBalones;
    private javax.swing.JLabel jLabelP1;
    private javax.swing.JLabel jLabelP2;
    private javax.swing.JLabel jLabelP3;
    private javax.swing.JLabel jLabelP4;
    private javax.swing.JLabel jLabelP5;
    private javax.swing.JLabel jLabelP6;
    private javax.swing.JLabel jLabelP7;
    private javax.swing.JLabel jLabelP8;
    private javax.swing.JLabel jLabelP9;
    private javax.swing.JLabel jLabelS1;
    private javax.swing.JLabel jLabelS2;
    private javax.swing.JLabel jLabelS3;
    private javax.swing.JLabel jLabelS4;
    private javax.swing.JLabel jLabelS5;
    private javax.swing.JLabel jLabelS6;
    private javax.swing.JLabel jLabelS7;
    private javax.swing.JLabel jLabelS8;
    private javax.swing.JLabel jLabelS9;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JTextField jTextFieldC1;
    private javax.swing.JTextField jTextFieldC2;
    private javax.swing.JTextField jTextFieldC3;
    private javax.swing.JTextField jTextFieldC4;
    private javax.swing.JTextField jTextFieldC5;
    private javax.swing.JTextField jTextFieldC6;
    private javax.swing.JTextField jTextFieldC7;
    private javax.swing.JTextField jTextFieldC8;
    private javax.swing.JTextField jTextFieldC9;
    // End of variables declaration//GEN-END:variables
}
